name: Auto labeling
on: [pull_request]

jobs:
  assign:
    name: Auto labeling
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
    steps:
      - name: Add feature label
        if: ${{ startsWith(github.head_ref, 'feat/') }}
        env:
          NUMBER: ${{ github.event.pull_request.number }}
        run: gh pr edit $NUMBER --add-label feature

      - name: Add chore label
        if: ${{ startsWith(github.head_ref, 'chore/') }}
        env:
          NUMBER: ${{ github.event.pull_request.number }}
        run: gh pr edit $NUMBER --add-label chore

      - name: Add release label
        if: ${{ startsWith(github.head_ref, 'release/') }}
        env:
          NUMBER: ${{ github.event.pull_request.number }}
        run: gh pr edit $NUMBER --add-label release

      - name: Add bug label
        if: ${{ startsWith(github.head_ref, 'bug/') }}
        env:
          NUMBER: ${{ github.event.pull_request.number }}
        run: gh pr edit $NUMBER --add-label bug

      - name: Add documentation label
        if: ${{ startsWith(github.head_ref, 'document/') }}
        env:
          NUMBER: ${{ github.event.pull_request.number }}
        run: gh pr edit $NUMBER --add-label documentation

      - name: Add environment label
        if: ${{ startsWith(github.head_ref, 'environment/') }}
        env:
          NUMBER: ${{ github.event.pull_request.number }}
        run: gh pr edit $NUMBER --add-label environment

      - name: Check changed file paths
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            backend:
              - 'apps/backend/**'
            frontend:
              - 'apps/frontend/**'
            lambda:
              - 'apps/lambda/**'
      - name: Add backend label
        if: steps.changes.outputs.backend == 'true'
        env:
          NUMBER: ${{ github.event.pull_request.number }}
        run: gh pr edit $NUMBER --add-label backend

      - name: Add frontend label
        if: steps.changes.outputs.frontend == 'true'
        env:
          NUMBER: ${{ github.event.pull_request.number }}
        run: gh pr edit $NUMBER --add-label frontend

      - name: Add lambda label
        if: steps.changes.outputs.lambda == 'true'
        env:
          NUMBER: ${{ github.event.pull_request.number }}
        run: gh pr edit $NUMBER --add-label lambda
