name: Auto labeling
on: [pull_request]

jobs:
  assign:
    name: Auto labeling
    runs-on: ubuntu-20.04
    steps:
      - run: echo $BRANCH_NAME
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          BRANCH_NAME: ${{ github.head_ref }}
      - run: gh pr edit $NUMBER --add-label feature
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          BRANCH_NAME: ${{ github.head_ref }}
        if: ${{ startsWith($BRANCH_NAME, 'feat/') }}
      - run: gh pr edit $NUMBER --add-label chore
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          BRANCH_NAME: ${{ github.head_ref }}
        if: ${{ startsWith($BRANCH_NAME, 'chore/') }}
      - run: gh pr edit $NUMBER --add-label release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          BRANCH_NAME: ${{ github.head_ref }}
        if: ${{ startsWith($BRANCH_NAME, 'release/') }}
      - run: gh pr edit $NUMBER --add-label bug
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          BRANCH_NAME: ${{ github.head_ref }}
        if: ${{ startsWith($BRANCH_NAME, 'bug/') }}
      - run: gh pr edit $NUMBER --add-label documentation
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          BRANCH_NAME: ${{ github.head_ref }}
        if: ${{ startsWith($BRANCH_NAME, 'document/') }}
      - run: gh pr edit $NUMBER --add-label environment
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          BRANCH_NAME: ${{ github.head_ref }}
        if: ${{ startsWith($BRANCH_NAME, 'environment/') }}
