name: Auto labeling
on: [pull_request]

jobs:
  assign:
    name: Auto labeling
    runs-on: ubuntu-20.04
    steps:
      - run: gh pr edit $NUMBER --add-label feature
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
        if: ${{ startsWith(github.head_ref, 'feat/') }}
      - run: gh pr edit $NUMBER --add-label chore
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
        if: ${{ startsWith(github.head_ref, 'chore/') }}
      - run: gh pr edit $NUMBER --add-label release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
        if: ${{ startsWith(github.head_ref, 'release/') }}
      - run: gh pr edit $NUMBER --add-label bug
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
        if: ${{ startsWith(github.head_ref, 'bug/') }}
      - run: gh pr edit $NUMBER --add-label documentation
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
        if: ${{ startsWith(github.head_ref, 'document/') }}
      - run: gh pr edit $NUMBER --add-label environment
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
        if: ${{ startsWith(github.head_ref, 'environment/') }}
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            backend:
              - 'apps/backend/**'
            frontend:
              - 'apps/frontend/**'
            lambda:
              - 'apps/lambda/**'
      - if: steps.changes.outputs.backend == 'true'
        run: gh pr edit $NUMBER --add-label backend
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
      - if: steps.changes.outputs.frontend == 'true'
        run: gh pr edit $NUMBER --add-label frontend
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
      - if: steps.changes.outputs.lambda == 'true'
        run: gh pr edit $NUMBER --add-label lambda
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
