name: Auto labeling
on: [pull_request]

jobs:
  assign:
    name: Auto labeling
    runs-on: ubuntu-20.04
    # if: ${{ github.actor != 'dependabot[bot]' && toJSON(github.event.pull_request.assignees) == '[]' }}
    steps:
      - run: gh pr edit $NUMBER --add-label chore
        # - run: gh pr edit $NUMBER --add-label $LABEL
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
      #     LABEL: ${{ github.event.pull_request.head.ref }}
      - run: echo $BRANCH_NAME.split('/')
        env:
          BRANCH_NAME: ${{github.head_ref}}
      - run: echo $BRANCH_NAME.split('/')[0]
        env:
          BRANCH_NAME: ${{github.head_ref}}
      - run: echo $BRANCH_NAME.split('/')[1]
        env:
          BRANCH_NAME: ${{github.head_ref}}
