name: Labeler
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
