name: Staging Deploy

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'リリース対象のタグ（未入力の場合最新タグ）'
        required: false
        default: ''
    branches: [main]
jobs:
  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Current Version
        id: current_version
        run: |
          git fetch --tags
          echo ::set-output name=VERSION::$( git describe --tags --abbrev=0)
        if: ${{ github.event.inputs.ref == '' }}

      - name: Get Input Version
        id: input_version
        run: |
          echo ::set-output name=VERSION::${{ github.event.inputs.ref }}
        if: ${{ github.event.inputs.ref != '' }}

      - name: Push branch
        env:
          BRANCH: staging
          CURRENT_VERSION: ${{ steps.current_version.outputs.VERSION }}
          INPUT_VERSION: ${{ steps.input_version.outputs.VERSION }}
        run: |
          git fetch --tags
          git switch -c ${BRANCH}-${CURRENT_VERSION}${INPUT_VERSION} origin/main
          git reset --hard ${CURRENT_VERSION}${INPUT_VERSION}
          git push -u origin ${BRANCH}-${CURRENT_VERSION}${INPUT_VERSION} -f
      - name: Create pull request
        uses: actions/github-script@v6
        env:
          BRANCH: staging
          CURRENT_VERSION: ${{ steps.current_version.outputs.VERSION }}
          INPUT_VERSION: ${{ steps.input_version.outputs.VERSION }}
        with:
          # github-token: ${{ secrets.VEGA_BOT_API_TOKEN }}
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `bump ${process.env.BRANCH} ${process.env.CURRENT_VERSION}${process.env.INPUT_VERSION}`,
              body: `Bump ${process.env.BRANCH} ${process.env.CURRENT_VERSION}${process.env.INPUT_VERSION}`,
              head: `${process.env.BRANCH}-${process.env.CURRENT_VERSION}${process.env.INPUT_VERSION}`,
              base: process.env.BRANCH
            })

# script: |
#             github.rest.pulls.create({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               title: `bump ${process.env.BRANCH} v${process.env.VERSION}`,
#               body: `Bump ${process.env.BRANCH} v${process.env.VERSION}`,
#               head: `${context.repo.owner}:${process.env.BRANCH}-v${process.env.VERSION}`,
#               base: process.env.BRANCH
#             })
