name: Staging Deploy

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'リリース対象のタグ'
        required: false
        default: ''
    branches: [main]
jobs:
  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Fetch Tags
      #   run: git fetch --tags

      - name: Get version
        id: get_version
        run: |
          if [ ${{ github.event.inputs.ref != '' }} ]; then
              echo ::set-output name=VERSION::${{ github.event.inputs.ref }}
          else
              git fetch --tags
              echo ::set-output name=VERSION::$(git describe --tags --abbrev=0)
          fi

      - name: Test
        run: echo ${{ steps.get_version.outputs.VERSION }}

      - name: Checkout Target Tag Version
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: git checkout ${VERSION}

      - name: Push branch
        env:
          BRANCH: staging
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          git switch -c ${BRANCH}-${VERSION} origin/main
          git push -u origin ${BRANCH}-${VERSION}
      - name: Create pull request
        uses: actions/github-script@v6
        env:
          BRANCH: staging
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        with:
          # github-token: ${{ secrets.VEGA_BOT_API_TOKEN }}
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `bump ${process.env.BRANCH} v${process.env.VERSION}`,
              body: `Bump ${process.env.BRANCH} v${process.env.VERSION}`,
              head: `${context.repo.owner}:${process.env.BRANCH}-v${process.env.VERSION}`,
              base: process.env.BRANCH
            })
