name: Staging Deploy

on:
  workflow_dispatch:
    branches: [main]
jobs:
  deploy:
    name: Deploy staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current version
        id: current_version
        run: |
          git fetch --tags
          echo ::set-output name=VERSION::$( git describe --tags --abbrev=0)

      - name: Switch to target version
        env:
          CURRENT_VERSION: ${{ steps.current_version.outputs.VERSION }}
        run: |
          git switch -c release/staging-${CURRENT_VERSION} origin/main
          git reset --hard ${CURRENT_VERSION}

      - name: Push branch
        env:
          CURRENT_VERSION: ${{ steps.current_version.outputs.VERSION }}
        run: git push -u origin release/staging-${CURRENT_VERSION} -f

      - name: Create pull request
        uses: actions/github-script@v6
        env:
          CURRENT_VERSION: ${{ steps.current_version.outputs.VERSION }}
        with:
          # github-token: ${{ secrets.VEGA_BOT_API_TOKEN }}
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Bump staging ${process.env.CURRENT_VERSION}`,
              body: `Bump staging ${process.env.CURRENT_VERSION}`,
              head: `release/staging-${process.env.CURRENT_VERSION}`,
              base: main
            })

# script: |
#             github.rest.pulls.create({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               title: `bump staging v${process.env.VERSION}`,
#               body: `Bump staging v${process.env.VERSION}`,
#               head: `${context.repo.owner}:staging-v${process.env.VERSION}`,
#               base: process.env.BRANCH
#             })
